name: Test package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install reqs
        run: pip3 install .
      - name: Run tests
        run: pytest test/test_PackageSnippet1.py -s
